# Generated by Django 3.1.4 on 2020-12-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agen', '0002_auto20200829_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
